micronaut:
  application:
    name: quickstart
  server:
#    If there is no environment variable, port 8080 is used
    port: ${SERVER_PORT:8080}
netty:
  default:
    allocator:
      max-order: 3
hello:
  world:
    message: "Hello from application.yml!"